### ISSUE TITLE
Where is the factory?

### ISSUE THREAD

**Issue by daddykotex** [mnubo/mnubo-java-sdk#5]
Where is located the factory used in the example?

```
com.mnubo.java.sdk.client.services.MnuboSDKFactory
```
And can you look at the models from the ingestion project to see how you can avoid to write your deserializer manually? This technique is not very extensible if we have more fields to the SmartObject, Owner or Event.

**Comment by dmasse76** [comment]
@daddykotex , I think we should update the serializer and deserializer in ingestion instead.  The issue is that @JsonAnySetter, which is used in ingestion, prevent us of doing immutable object.  SmartObject, Owner and Event are value that should not be modifed once created.

**Comment by daddykotex** [comment]
Maybe there is another way around this? Because if you look closely at the serializer and deserializer classes (I wrote them for ingestion at first) it's gonna be a testing and debugging nightmare if those entities get somewhat more complex.

Maybe we could have a clean object with the proper jackson annotations that could be used in a builder to get the final entity?
